name        'garethr-nginx'
version     '0.0.1'
source      'git://github.com/garethr/garethr-nginx.git'
author      'Gareth Rushgrove'
summary     'Module for installing (not configuring) nginx'
description 'Install nginx'
license     'Apache License, Version 2.0'

dependency  'puppetlabs/apt', '>= 1.1.0'
dependency  'puppetlabs/stdlib', '>=4.1.0'
